version: "3.9"
services:
    web:
        build: .
        command: /code/run.sh
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db.curiescience.com
    db.curiescience.com: # Note that this 
        image: postgres:13
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - "POSTGRES_PASSWORD=curiescience"
            - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
        postgres_data:
