version: "3.9"
services:
    web:
        build: .
        command: /code/run.sh
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db
    db:
        image: postgres:13
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"
    portainer:
        image: portainer/portainer-ce:latest
        ports:
            - 9443:9443
        volumes:
            - data:/data
            - /var/run/docker.sock:/var/run/docker.sock
        restart: unless-stopped
volumes:
        postgres_data:
        data: