name: Build and Push Trunk

on:
  push:
    branches: [main]

jobs:
  build-trunk:
    runs-on: ubuntu-latest
    name: Build Trunk
    steps:
      # Prepare Environment
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set Environment Variables
        uses: ./.github/actions/setenv
      - name: Login to CoC-Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY_HOST }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: generate docker tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKER_REGISTRY_HOST }}/${{ env.DOCKER_REGISTRY_REPO }}/${{ env.DOCKER_REGISTRY_IMAGE }}
          tags: |
            type=raw,value=develop

      # Build Docker Images (amd64 and arm64)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          # use this to also build for arm64 (Apple M1, M2 or Raspberry Pi 3/4/5)
          # platforms: linux/amd64,linux/aarch64
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}